-- Run this once in Supabase SQL Editor before using the Supabase backend.

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  title text,
  file_path text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.clips (
  id bigint generated by default as identity primary key,
  video_id bigint not null references public.videos(id) on delete cascade,
  file_path text not null unique,
  start_sec double precision,
  end_sec double precision,
  duration_sec double precision,
  type text not null check (type in ('technique', 'concept')),
  title text,
  description text,
  is_favorite boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  facet text not null,
  name text not null,
  path text,
  is_allowed integer not null default 0,
  unique (facet, name)
);

create table if not exists public.clip_tags (
  clip_id bigint not null references public.clips(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (clip_id, tag_id)
);

create table if not exists public.video_tags (
  video_id bigint not null references public.videos(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (video_id, tag_id)
);

create index if not exists idx_clips_video_id on public.clips(video_id);
create index if not exists idx_tags_facet_name on public.tags(facet, name);
create index if not exists idx_clip_tags_tag_id on public.clip_tags(tag_id);
create index if not exists idx_video_tags_tag_id on public.video_tags(tag_id);
